DOMAIN = "legacycam"

CONF_NAME = "name"
CONF_IP = "ip"
CONF_RECORDING_SEGMENT_SECONDS = "recording_segment_seconds"
CONF_RECORDING_RETENTION_HOURS = "recording_retention_hours"
CONF_RECORDING_PATH = "recording_path"
CONF_MOTION_THRESHOLD = "motion_threshold"
CONF_MOTION_SAMPLE_INTERVAL = "motion_sample_interval"
CONF_MOTION_FLASH_HOLD_SECONDS = "motion_flash_hold_seconds"

DEFAULT_NAME = "LegacyCam"
DEFAULT_PORT = 8080
DEFAULT_TIMEOUT = 5
UPDATE_INTERVAL_SECONDS = 30
DEFAULT_RECORDING_SEGMENT_SECONDS = 30
DEFAULT_RECORDING_RETENTION_HOURS = 2
DEFAULT_RECORDING_PATH = "www/legacycam"
DEFAULT_MOTION_THRESHOLD = 6
DEFAULT_MOTION_SAMPLE_INTERVAL = 1.0
DEFAULT_MOTION_FLASH_HOLD_SECONDS = 10

ENDPOINT_STREAM = "/stream"
ENDPOINT_FLASH_ON = "/flash/on"
ENDPOINT_FLASH_OFF = "/flash/off"
ENDPOINT_FLASH_STATUS = "/flash/status"
ENDPOINT_STATUS = "/status"
ENDPOINT_PING = "/ping"

MANUFACTURER = "LegacyCam"
MODEL = "iPhone 4 Camera"
